version: '3.9'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./frontend/:/app
    environment:
      NODE_ENV: $NODE_ENV
      CHOKIDAR_USEPOLLING: 1

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    volumes:
      - ./backend/:/app
    environment:
      NODE_ENV: $NODE_ENV
